### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#19]
(replaced issue #10)

Need a packaging system.
- PyPI - widely used for Python.
- autotools - might be required for GNOME

I'm sure there are others, feel free to add.

**Comment by kevin-brown** [comment]
More information on Python-based packaging:
http://stackoverflow.com/q/6344076/359284

I usually use `setuptools` for no particular reason, but you can [find](https://github.com/search?q=setup.py) [tons](https://github.com/tomchristie/django-rest-framework/blob/master/setup.py) [of](https://github.com/Rediker-Software/doac/blob/master/setup.py) [examples](https://github.com/getsentry/sentry/blob/master/setup.py) [around](https://github.com/lebinh/ngxtop/blob/master/setup.py).  It will even set up the console script automatically.

~~I'm not familiar with packaging software for distribution outside of PyPI (or other language-specific indexes), so I'm not aware of other tools.~~

Most of the GNOME-related distribution guides point at autotools and automake being required.

# Related links for reading:

## Debian / Ubuntu
- http://stackoverflow.com/q/16911711/359284
- http://packaging.ubuntu.com/html/packaging-new-software.html
- https://www.debian.org/doc/packaging-manuals/python-policy/index.html
- https://www.debian.org/doc/debian-policy/ch-controlfields.html

## Fedora
- https://fedoraproject.org/wiki/Packaging:Guidelines
- https://fedoraproject.org/wiki/Packaging:Python
