### ISSUE TITLE
A number of parameters need to be identified and made readable in gui.py

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#2]
Look for the #FIXME markers in src/mousetrap/gui.py

**Comment by kevin-brown** [comment]
My guess is that the call matches the documentation at
https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-data

Keep in mind that this is not the same as the PyGTK 2 documentation, which does not include these parameters:
http://www.pygtk.org/pygtk2reference/class-gdkpixbuf.html#function-gdk--pixbuf-new-from-data

**Comment by StoneyJackson** [comment]
Thank you
