### ISSUE TITLE
Raise clearer exceptions for configuration problems

### ISSUE THREAD

**Issue by kevin-brown** [GNOME-MouseTrap/mousetrap#23]
RIght now if a user includes the path to a plugin which cannot be imported, the standard Python `ImportError` is raised.  While this is useful, it's not always clear that the problem is with the configuration and not with MouseTrap itself.

Django uses an `ImproperlyConfigured` exception for these cases and provides a more clear description of the issue.

https://docs.djangoproject.com/en/dev/ref/exceptions/#improperlyconfigured

**Comment by StoneyJackson** [comment]
I don't think we can claim its a configuration error; i.e., a problem with the config file. It could also be a miss configuration of the Python environment; i.e., the Python import search path.

I've added an error message. But the original exception is still raised.
