### ISSUE TITLE
WANTED: spike implementation of a motion tracker

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#3]
I want a working motion tracker. Quick and dirty. The simpler the better.

My plan was to implement the one described in the video below. But I ran out of time.

http://www.youtube.com/watch?v=X6rPdRZzgjg

It doesn't have to be that algorithm. Any will do. Don't worry about being perfect or pretty (for now). Simple is preferred over bells and whistles.

**Comment by kevin-brown** [comment]
I've got a bruteforce implementation of a face tracker here:
https://gist.github.com/kevin-brown/9611443

It's ["self-documenting"](https://imgur.com/gallery/M5wl14r) (my bad) and I can't guarentee that it still works (currently need to rebuild my OpenCV install), but it did work (relatively) well a few months ago when it was written.  Like you, I had plans to implement a better one to replace that and also ran out of time.

**Comment by StoneyJackson** [comment]
oooo..... I'm all for self-documenting, and I don't mind helping to make it more self-documenting. I'll give it a try.

**Comment by StoneyJackson** [comment]
I need to get an IRC client for my Fed20 install. Suggestions?

In the mean-time, do you have the *mcs*.xml files?

**Comment by kevin-brown** [comment]
All of the haar cascades should be available at https://github.com/Itseez/opencv/tree/master/data/haarcascades.

> I need to get an IRC client for my Fed20 install. Suggestions?

I personally use [Quassel](http://quassel-irc.org/downloads), but tons of people recommend [HexChat](https://apps.fedoraproject.org/packages/hexchat).  There is always [Mibbit](http://www.mibbit.com/) if you feel like skipping the install.
