### ISSUE TITLE
Absolute path error on `pip install .`

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#31]
On branch `autotools2`

Are we maintaining pip compatibility. Or are we just using setup.py to implement autotools packaging?

**Comment by kevin-brown** [comment]
Fixed in https://github.com/GNOME-MouseTrap/mousetrap/commit/b89161dc6a7cf831d02e17c965319da86a336775, the break wasn't intentional.

**Comment by StoneyJackson** [comment]
Thank you! Works perfectly now :)
