### ISSUE TITLE
distcheck fails when generating the ChangeLog

### ISSUE THREAD

**Issue by kevin-brown** [GNOME-MouseTrap/mousetrap#33]
`make distcheck` fails when generating the ChangeLog because the file used to generate it is not included in the distribution.  Considering these files are not that complex, it may be better if we just move the commands from the individual files into the Makefile.

Full output is available in the following Gist:
https://gist.github.com/kevin-brown/8f1d959c603a0af1d8cf

**Comment by StoneyJackson** [comment]
Fixed.
