### ISSUE TITLE
Convert `bin` commands into Makefile targets?

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#35]
Responding to "Do we want to do this with the other files in `bin` like this?" in #34.

Most developers know make files. We could document some custom hooks like:
- veryclean  (all files ignored by git)
- pristine (all files ignored or not tracked by git)
- pot  (regenerate POT file)
- run  (an in-place run)
- test  (run tests)
- pylint  (run pylint)

The disadvantage is that they cannot be ran from anywhere. During development, I like to be able to run all the tests, or run moustrap in-place, from anywhere in the code base.

**Comment by kevin-brown** [comment]
I definitely agree with `make test` and `make pot` (`make translation`? `pot` looks odd and not actually clear as a command) considering developers should be able to run them when they only have the distribution package.  The rest... I'm sitting between [+0/-0](https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/#how-we-make-decisions) on.

> The disadvantage is that they cannot be ran from anywhere.

I'm not sure what the difference would be here (with the exception of running MT in-place)?

**Comment by StoneyJackson** [comment]
Targets:
- [x] `make clean` (update to delete *.pyc, *.pyo, *.mo) [kevin]
- [x] `make pristine` (delete everything not under VC) [stoney]
- [x] `make potfile` (generate pot file) [stoney]
- [x] `make mofiles` (generate *.mo from *.po) [stoney]
- [x] `make check`  (run tests) [stoney]
- [x] `make lint`  (run pylint) [stoney]
- [x] `make run`  (in-place run) [stoney]

[EDIT: @kevin-brown OK, the checkboxes are cool!

**Comment by StoneyJackson** [comment]
`make run` and `make test` need dependencies and should do something about needing PYTHONPATH declared.
