### ISSUE TITLE
Feature detection sharing

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#36]
This is not necessary before release of 1.0.0-a. I just don't want to forget it.

I think the same feature is detected multiple times on the same image (need to confirm). I'm not sure how much of a performance hit this is, but it is unnecessarily spamming the INFO feed.

I recommend implementing a factory for FeatureDetector that returns the same instance for the same named feature (which maps to the same haar cascade file). Then update the implementation of FeatureDetector to cache images that it has detected on. Add a clear_cache() method that could be called by an additional plugin at the end of each loop (allowing images to be collected).

``` python
eye = FeatureDetector.get('left_eye')  # gets the singleton left-eye detector
...
eye.detect(image)  # returns/raises cached result if exists, otherwise calculates, caches, and returns/raises
...
# in new ClearFeatureDetectorPlugin
for detector in FeatureDetector.detectors():
    detector.clear_cache()
```

``` yaml
assembly:
  # as the last plugin
  - mousetrap.plugins.clear_feature_detector.ClearFeatureDetectorPlugin
```

**Comment by kevin-brown** [comment]
I think in the long run this is probably going to be needed, though care will be needed to make sure that data isn't incorrectly cached.

> I'm not sure how much of a performance hit this is, but it is unnecessarily spamming the INFO feed.

Right now, it's probably not hurting the performance that much.  I haven't had that much of an issue with it spamming my console, though that may be a sign that the output should be moved to a different level (such as DEBUG).
