### ISSUE TITLE
OpenCV alternatives

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#42]
To allow us to finish porting to Python3, we need to consider alternatives to OpenCV (since it is not Python3 compatible... yet).

**Comment by kevin-brown** [comment]
My original guess was [SimpleCV](http://simplecv.org/), but that is actually just a wrapper around OpenCV, so it has the same issues.

**Comment by paxnovem** [comment]
I looked into some alternatives, but they are pretty sparse. OpenCV is by far the most mature and most documented of the libraries I found. The vxl project was the only other decent library but I can't tell if they have python bindings: http://sourceforge.net/projects/vxl/ Originally SimpleCV was my favorite as well, but came across the same issue as @kevin-brown. I believe we may just need to wait for opencv to release version 3. Though, has it been considered to include the git version of opencv as a included (bundled) binary until they finally release?

**Comment by kevin-brown** [comment]
> The vxl project was the only other decent library but I can't tell if they have python bindings: http://sourceforge.net/projects/vxl/

They do appear to have Python bindings, but it doesn't look like they have Python 3 bindings.

> Though, has it been considered to include the git version of opencv as a included (bundled) binary until they finally release?

While a git submodule would work, we would need to include instructions for compiling OpenCV for Python 3 which isn't ideal.

**Comment by HeidiEllis** [comment]
Looks like OpenCV is moving. 3 alpha has been released.
