### ISSUE TITLE
Link from github Developer Documentation to GNOME MouseTrap site

### ISSUE THREAD

**Issue by HeidiEllis** [GNOME-MouseTrap/mousetrap#46]
The developer (and user) documentation is located on the GNOME MouseTrap site (https://wiki.gnome.org/Projects/MouseTrap). We need a statement/paragraph on the github MouseTrap wiki indicating so and including a link to the GNOME site.

**Comment by StoneyJackson** [comment]
Isn't that what is under the "Developer" section? Or my question is probably, "what is needed beyond what is under the Developer section?"

**Comment by StoneyJackson** [comment]
Feel free to reopen if I'm wrong.
