### ISSUE TITLE
Why can't pylint find cv constants?

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#6]
When I run bin/mt-pylint from project root, I'm seeing

```
************* Module mousetrap.vision
...
E: 32,24: Module 'cv' has no 'CV_CAP_PROP_FRAME_WIDTH' member (no-member)
E: 33,24: Module 'cv' has no 'CV_CAP_PROP_FRAME_HEIGHT' member (no-member)
```

But I have no problem finding them manually through thy Python interactive shell:

```
22:16 $ python
Python 2.7.5 (default, Feb 19 2014, 13:47:28) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv
>>> cv.CV_CAP_PROP_FRAME_WIDTH
3
```

So what's pylint's problem?

**Comment by kevin-brown** [comment]
I'm pretty sure these are dynamically assigned, so PyLint can't statically determine if they exist.  There may be a way to ignore these, similar to how [PyLint allows you to exclude classes](https://github.com/GNOME-MouseTrap/mousetrap/pull/1/files#diff-66fafcb2b5419f12fa5602b19856b8f1R196), but I do not have a lot of experience with PyLint.
